# Example 3: Code Injection Vulnerability
name: Code Injection Demo
on:
  issues:
    types: [opened]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # VULNERABLE: User input directly in run context
      - name: Run user-provided script
        run: |
          echo "Running user script"
          ${{ github.event.issue.body }}
